### ISSUE TITLE
Scattare foto utili per il sito

### ISSUE THREAD

**Issue by Rickyz03** [The-TecWebers/Progetto#6]
Enrico farà le foto lunedì di:
- Attrezzature e Parco macchine
- Foto per la home
- Foto per la storia
Massima qualità possibile, sia in verticale sia in orizzontale.

**Comment by CcEnrico** [comment]
scattate foto parco macchine, raccolte foto storiche e organizzate in storia lavori

**Comment by CcEnrico** [comment]
le foto dell'attrezzatura non sono fondamentali e eviterei metterne molte utilizziamo quelle che gia abbiamo se vogliamo metterle, ma eviterei e metterei poche o addirittura nessuna foto sull'attrezzatura per non rendere la pagina di atrezzatura e parco macchine pesante

**Comment by CcEnrico** [comment]
mancano solo quelle della home
